### ISSUE TITLE
Scale while rendering geometry

### ISSUE THREAD

**Issue by ReneHollander** [topobyte/osm4j-core#1]
Hello,

I am wondering how to set the scale for the rendering of elements. In my case I need it, so that 1 pixel on the canvas is 1 meter. I am working off the MapRendering example.

Best regards,
René Hollander

**Comment by sebkur** [comment]
Hi René,

The `MercatorImage` has a [getWorldSize()](http://www.jaryard.com/javadoc/de.topobyte/mercator-image/0.0.1/de/topobyte/mercator/image/MercatorImage.html#getWorldSize--) method that can be used to determine the number of pixels that the whole world would take up with the current zoom level at the current latitude. In combination with the circumference of the planet of 40075016.686 meters, you can determine the number of meters per pixel. Note that because of the distortion of the mercator projection, this depends on the latitude.

To do the reverse, what you would like to do, you would have to come up with an appropriate bounding box to use for the `MercatorImage`. If, for example, you know the center of the bounding box you would like to display, you can determine the bounding box based on the size of your view in pixels using cross multiplication. 360° correspond to 40075016.686 meters and if your view is `x` pixels wide then you want to display `x` meters and can hence determine the number of degrees of longitude that your bounding box should be wide. I think the formula for the width of the bounding box would then be `lon = x / 40075016.686 * 360`.

You can set the latitude range to a very small value to let the longitude range determine the resulting bounding box of the view or come up with a similar calculation for the latitude as well.

Hope this helps,
Sebastian

**Comment by ReneHollander** [comment]
Hello Sebastian,

thank you for your reply, but I have some issues:
I used the following parameters for the calculation that you provided:

```
CIRCUMFERENCE_EARTH = 40075016.686
width = 1000
height = 1000
center = 16.321422, 48.307742
```

Then I used the following calculations to determine the projection:

``` java
double lon_range = width / CIRCUMFERENCE_EARTH * 360.0;
double lat_range = lon_range / 2; // Using lon_range as a small value

bbox = new BBox(center.getLongitude() + lon_range / 2, center.getLatitude() - lat_range / 2, center.getLongitude() - lon_range / 2, center.getLatitude() + lat_range / 2);
mercatorImage = new MercatorImage(bbox, width, height);
```

This yields the following results:

```
lon_range: 0.008983152841100728
lat_range: 0.004491576420550364
bbox: 16.316930,48.309988:16.325914,48.305496
MercatorImage{width=1000, height=1000, mlon1=16.316930423579446, mlat1=48.30998778821027, mlon2=16.32591357642055, mlat2=48.30549621178972, worldsize=4.007501668595389E7, sx=2.1853900729056098E7, sy=1.3878802636580467E7}
```

I rendered the result to an image: http://imgur.com/a/S0Vb9
- Rene Hollander

**Comment by sebkur** [comment]
Ah, yeah, that calculation only works at the equator. All circles parallel to the equator are of course shorter. Sorry, I do not have the calculation at hand but I think the **haversine formula** will allow you to calculate the length of the circle at the given latitude and when you plug that into your calculation it should work.

**Comment by sebkur** [comment]
Or it's even simpler. The [Wikipedia](https://en.wikipedia.org/wiki/Circle_of_latitude) says:

> Their length can be calculated by a common sine or cosine function. The 60th circle of latitude is half as long as the equator (disregarding Earth’s minor ovality, which is less than 0.3%)

**Comment by ReneHollander** [comment]
Thank you for your input! I solved it by multiplying the circumference at the equator with the cosine of the latitude of the center point:

``` java
double circumference_lat = 40075016.686 * Math.cos(Math.toRadians(48.307742));
```
- Rene Hollander
