### ISSUE TITLE
HashMap-like methods for getting tags

### ISSUE THREAD

**Issue by Nixill** [topobyte/osm4j-core#3]
The tags of an Entity have a data model are much like a Map<String, String> - for any given tag (key), there may or may not be a value, but if there is, there's only one.

As such, I believe Entity should have the following methods for getting the values of tags a lot more efficiently than current methods:

* `getAllTags()` - Returns a `Map<String, String>` of all the tags the object has.
* `hasTag(String key)` - Returns a `boolean` - Checks whether the OsmEntity has a tag by the given name.
* `getTag(String key)` - Returns a `String` - Retrieves the value of the tag `key`, or `null` if there's no such value.
* `putTag(String key, String tag)` - Returns the previous value of the tag, if anything - Sets the tag by name (or removes it if `tag` is null or an empty string).
* `delTag(String key)` - Returns the previous value of the tag, if anything - Deletes the tag from the Entity.

(OsmEntity should also have the first three)

Edit: A word.

**Comment by sebkur** [comment]
These methods are intentionally left out for keeping both processing time and required memory to a minimum. When processing large data sets it can become quite significant, at least in terms of processing time, what is executed for each Entity. Some applications require a Map-like model of the tags and others don't, which is why the computation of a Map is not performed as a standard action to allow for maximum performance in the former case. I do realize that having a Map-like view on the tags is a very common operation though, which is why there's a utility class [OsmModelUtil](http://jaryard.com/javadoc/de.topobyte/osm4j-core/0.0.20/de/topobyte/osm4j/core/model/util/OsmModelUtil.html), which has the method `getTagsAsMap()`, accepting an `Entity` and returning a `Map<String, String>`, which can be manipulated using standard map operations. This is fine for data-consuming tasks, changes to the map won't be reflected in the Entity though. If you need to manipulate Entities, you actually need to create new instances of `Node`, `Way` and `Relation` from the [core/model/impl](http://jaryard.com/javadoc/de.topobyte/osm4j-core/0.0.20/de/topobyte/osm4j/core/model/impl/package-summary.html) package.
